# Generated by Django 3.1 on 2021-05-30 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_message',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
