# Generated by Django 3.1 on 2021-06-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210618_2118'),
        ('chat', '0003_inscreenhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='message/photos'),
        ),
        migrations.AddField(
            model_name='message',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='inscreenhistory',
            unique_together=set(),
        ),
    ]
