# Generated by Django 3.1 on 2021-05-30 06:45

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_auto_20210529_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 30, 6, 45, 44, 376522, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='storystream',
            unique_together={('user', 'following_user')},
        ),
    ]
